baseURL = "http://yasoob.me/"
languageCode = "en-us"
title = "Yasoob Khalid"
author = "yasoob"
theme = "hugo-zen"
copyright = "CC-by-NA"
enableEmoji = true
googleanalytics = "UA-97849776-1"

[params]
	logo = "/images/profile.jpg"
	email = "hi@yasoob.me"
	twitter = "https://twitter.com/yasoobkhalid"
	github = "https://github.com/yasoob"
	linkedin = "https://www.linkedin.com/in/yasoob/"
	tagline = "A personal blog on all kinds of musings"
[taxonomies]
  category = "categories"

